package com.grey.database

import com.grey.environment.LocalSettings


class TableVariables {

  private val localSettings = new LocalSettings()

  /**
    * Ref. https://dev.mysql.com/doc/refman/8.0/en/load-data.html
    *
    * @param isLocal: true | false -> is the file locally located (true) or hosted within a server (false)
    * @param infile: The path to the file location; it includes the file name & extension
    * @param duplicates: Duplicates: REPLACE | IGNORE
    * @return
    */
  def tableVariables(isLocal: Boolean = false,
                     infile: String = "", duplicates: String = ""): Map[String, String] = {


    // Table name
    val tableName = "rides"


    // String of fields
    val fields: String = localSettings.fieldsOfInterest.mkString(start = "(", sep = ", ", end = ")")


    // Create statement
    // Remember the inherent parallel aspects:
    //    https://www.postgresql.org/docs/10/runtime-config-resource.html#GUC-MAX-WORKER-PROCESSES
    val stringCreateTable: String =
      s"""
         |CREATE TABLE IF NOT EXISTS $tableName (
         |    ${tableName}_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
         |    started_at TIMESTAMP NOT NULL,
         |    start_station_id VARCHAR(15) NOT NULL,
         |    ended_at TIMESTAMP DEFAULT NULL,
         |    end_station_id VARCHAR(15) DEFAULT NULL,
         |    duration BIGINT DEFAULT NULL,
         |    start_date DATE NOT NULL,
         |    start_date_epoch BIGINT NOT NULL
         |    );
         |
         |    COMMENT ON COLUMN $tableName.started_at IS 'The start date and time of the ride';
         |    COMMENT ON COLUMN $tableName.start_station_id IS 'The unique identifier of the start station' ;
         |    COMMENT ON COLUMN $tableName.ended_at IS 'The end date and time of the ride';
         |    COMMENT ON COLUMN $tableName.end_station_id IS 'The unique identifier of the end station';
         |    COMMENT ON COLUMN $tableName.duration IS 'The duration of the ride in seconds';
         |    COMMENT ON COLUMN $tableName.start_date IS 'The date the ride started';
         |    COMMENT ON COLUMN $tableName.start_date_epoch IS 'UNIX Epoch from 1 January 1970 00 00 00 UTC';
       """.stripMargin


    // Statement
    val uploadString =
      s"""
         |COPY $tableName $fields FROM '$infile' WITH
         |CSV
         |DELIMITER ','
         |HEADER
         |QUOTE '"'
         |ENCODING 'UTF8'
       """.stripMargin
    println(uploadString.toString)


    // Hence
    Map("stringCreateTable" -> stringCreateTable.toString, "uploadString" -> uploadString.toString,
      "tableName" -> tableName.toString)

  }


}
